


folder_path = '/Users/pengchengxie/Downloads/A-New-DFO-Method-Using-an-Improved-Model-main 2/newmodelnewes_xpc_yyx/newuoam'; % 更改为要更改文件的文件夹路径

% 列出文件夹中的所有MATLAB文件
files = dir(fullfile(folder_path, '*.m'));

% 循环处理每个文件
for i = 1:numel(files)
    % 检查文件是否为文件（不是文件夹）
    if ~files(i).isdir
        % 获取文件路径
        file_path = fullfile(files(i).folder, files(i).name);
        
        % 打开文件，添加标题信息，并保存
        fid = fopen(file_path, 'r');
        contents = fread(fid, '*char')';
        fclose(fid);
        
        % 插入标题信息到文件的顶部
        new_contents = sprintf('%s\n%s\n%s\n%s\n\n', ...
            '% A DFO Method Using a New Model', ...
            '% Codes for the paper entitled',... 
            '% "A Derivative-free Method Using a New Under-determined Quadratic Interpolation Model"', ...
            '% Copyright: Pengcheng Xie & Ya-xiang Yuan', ...
            '% Connect: xpc@lsec.cc.ac.cn', ...
            '% A DFO Method Using a New Model', ...
            '% ----------------------------------------------------------', ...
'% License Information', ...
'% ----------------------------------------------------------', ...
'% This code is distributed under the MIT License.', ...
'% You should have received a copy of the MIT License along', ...
'% with this program. If not, see <https://opensource.org/licenses/MIT>.', ...
'% For further information or questions, contact the authors', ...
'% via the provided email address.', ...
'% ----------------------------------------------------------', ...
'% Code Version Information', ...
'% ----------------------------------------------------------', ...
'% Version: 1.0', ...
'% Changes: Initial release.', ...
'% ----------------------------------------------------------', ...
'% ----------------------------------------------------------', ...
'% References', ...
'% ----------------------------------------------------------', ...
'% For more information, refer to the paper:', ...
'% "A Derivative-free Method Using a New Under-determined Quadratic Interpolation Model"', ...
'% by Pengcheng Xie & Ya-xiang Yuan.', ...
'%', ...
'% If you use this code in your research, please cite the above paper.', ...
'% ----------------------------------------------------------', ...
'% ----------------------------------------------------------', ...
'% Contributors', ...
'% ----------------------------------------------------------', ...
'% This code was written by Pengcheng Xie & Ya-xiang Yuan.', ...
'% ----------------------------------------------------------');
        
        new_contents = [new_contents contents];
        
        % 写入文件
        fid = fopen(file_path, 'w');
        fwrite(fid, new_contents);
        fclose(fid);
    end
end
